application:
  name: user-service
  version: 1.0.0
  environment: development

database:
  host: localhost
  port: 5432
  user: your_db_user
  password: your_db_password
  name: user_service_db

server:
  host: 0.0.0.0
  port: 8080

logging:
  level: info
  format: json

jwt:
  secret: your_jwt_secret
  expiration: 24h

email:
  smtp_server: smtp.example.com
  smtp_port: 587
  username: your_email@example.com
  password: your_email_password
  from_address: no-reply@example.com

features:
  enable_registration: true
  enable_password_reset: true