root = "src"
tmp_dir = "../.air_tmp"

[build]
cmd = "cd src && go build -o ../.air_tmp/main ."
bin = "/app/payment-service/.air_tmp/main"
include_ext = ["go"]
exclude_dir = ["../.air_tmp", "vendor"]
delay = 500

[log]
time = true
