FROM golang:1.23-alpine

WORKDIR /app

# Copy go.mod và go.sum từ root vào container
COPY go.mod ./
COPY go.sum ./
RUN go mod download

# Copy toàn bộ mã nguồn vào container
COPY . .

WORKDIR /app/search-service

RUN go build -o search-service .

EXPOSE 8086

CMD ["./search-service"]