FROM golang:1.25-alpine

WORKDIR /app

# Copy toàn bộ project (chứa product-service và module/gRPC-Product)
COPY . .

# Cài air (hot reload)
RUN go install github.com/air-verse/air@latest

WORKDIR /app/search-service

CMD ["air"]
